spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: 192.168.99.100:32770
    topic:
      userCreated: USER_CREATED_TOPIC

security:
  oauth2:
    client:
      clientId: micro-app
      clientSecret: eedca3b1-7170-402c-994f-370fa41445d6
      accessTokenUri: http://localhost:8180/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8180/auth/realms/demo/protocol/openid-connect/auth
      token-name: access_token
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://localhost:8180/auth/realms/demo/protocol/openid-connect/userinfo